nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8080
              description: API Summa
        info:
            title: API-Summa
            description: This is an awesome app!
            version: 1.0.0
            contact:
                email: joseagraz29@gmail.com
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/docs$)